export const Users = [
    {
      id:1,
      profilePicture: "assets/people/Img1.jpg",
      username: "Arthur Boyle ",
    },
    {
      id:2,
      profilePicture: "assets/people/Img2.jpg",
      username: "Shinra Kusakabe",
    },
    {
      id:3,
      profilePicture: "assets/people/Img3.jpg",
      username: "Edward Elric",
    },
    {
      id:4,
      profilePicture: "assets/people/Img4.jpg",
      username: "Juzo Suzuya",
    },
    {
      id:5,
      profilePicture: "assets/people/Img5.jpg",
      username: "Charlotte Katakuri",
    },
    {
      id:6,
      profilePicture: "assets/people/Img6.jpg",
      username: "Kozuki Oden",
    },
    {
      id:7,
      profilePicture: "assets/people/Img7.jpg",
      username: "Sasha Blaus",
    },
    {
      id:8,
      profilePicture: "assets/people/Img8.jpg",
      username: "Levi Ackerman",
    },
    {
      id:9,
      profilePicture: "assets/people/Img9.jpg",
      username: "Gojo Satoru",
    },
    {
      id:10,
      profilePicture: "assets/people/Img10.jpg",
      username: "Ryomen Sukuna",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/posts/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/posts/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/posts/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/posts/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/posts/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/posts/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/posts/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/posts/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/posts/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];